### ISSUE TITLE
Help needed with correct version tag.

### ISSUE THREAD

**Issue by jpurusho65** [hestonhoffman/changed-lines#3]
Hey, first thanks for this action script. I'm trying to use this and having trouble as shown below.

Run hestonhoffman/changed-lines@v1
/usr/bin/docker run --name c[7](https://github.com/jpurusho65/document/actions/runs/7401349666/job/20136915410#step:4:8)ad54b7e304e49[8](https://github.com/jpurusho65/document/actions/runs/7401349666/job/20136915410#step:4:9)3a4805b7c3a50eb8e15057_7dbce2 --label c7ad54 --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_BRANCH" -e "INPUT_REPO" -e "INPUT_PR" -e "INPUT_DELIMITER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/document/document":"/github/workspace" c7ad54:b7e304e4983a4805b7c3a50eb8e15057
Traceback (most recent call last):
  File "/app/main.py", line 88, in <module>
    added_line_data = parse_patch_data(data)
  File "/app/main.py", line 32, in parse_patch_data
    if entry['additions'] != 0:
TypeError: string indices must be integers

I tried using v1.1, but that appears to be invalid path. Do you have any recommendation on correct usage of this action script.
I used the exact example below:
on: [ pull_request ]

jobs:
  find_changed_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find changed lines
        id: changed_lines
        uses: hestonhoffman/changed_lines@v1
      - name: Print changed lines
        run: echo ${{ steps.changed_lines.outputs.changed_lines }}

Also, I think path must be changed-lines@v1 and not _.  Please let me know how to correctly use this action script.

**Comment by hestonhoffman** [comment]
Hi! Yes, you're right. It should be `uses: hestonhoffman/changed-lines@v1`. Sorry for the typo - I'll get that fixed

**Comment by hestonhoffman** [comment]
v1 should work - I'm using it in [this workflow](https://github.com/DataDog/documentation/blob/48a67d4782f7290c5a3b5dbe704165d7b49eb1cb/.github/workflows/vale_linter.yml#L31C1-L31C1)

But let me know if you're still having trouble and I'll try to investigate some more
